[[plugins]]
repo    = 'Shougo/unite.vim'

[[plugins]]
repo    = 'Shougo/neomru.vim'
on_source = ['unite.vim']

[[plugins]]
repo    = 'Shougo/vimfiler'

[[plugins]]
repo    = 'tell-k/vim-autopep8'
on_ft = ['python']

[[plugins]]
repo    = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo    = 'davidhalter/jedi-vim'
on_ft = ['python']

[[plugins]]
repo =  'scrooloose/syntastic'

